mkdir -p backend/medusa/src/api/admin/custom
mkdir -p backend/medusa/src/api/store/custom
mkdir -p backend/medusa/src/loaders
mkdir -p backend/medusa/src/modules/delivery/models
mkdir -p backend/medusa/src/modules/delivery/services
mkdir -p backend/medusa/src/modules/subscription/models
mkdir -p backend/medusa/src/modules/subscription/services
mkdir -p backend/medusa/src/modules/wholesale/models
mkdir -p backend/medusa/src/modules/wholesale/services
mkdir -p backend/medusa/src/subscribers
mkdir -p backend/medusa/src/workflows
mkdir -p backend/shared/src/constants
mkdir -p backend/shared/src/types
mkdir -p backend/shared/src/utils
mkdir -p backend/worker/src/clients
mkdir -p backend/worker/src/lib
mkdir -p backend/worker/src/processors/erp
mkdir -p backend/worker/src/processors/maintenance
mkdir -p backend/worker/src/processors/notifications
mkdir -p backend/worker/src/processors/orders
mkdir -p backend/worker/src/queues
mkdir -p docker/erpnext
mkdir -p docker/medusa
mkdir -p docker/nextjs
mkdir -p docker/nginx
mkdir -p docker/worker
mkdir -p docs/api
mkdir -p docs/runbooks
mkdir -p frontend/src/app/\(account\)/addresses
mkdir -p frontend/src/app/\(account\)/orders/\[id\]
mkdir -p frontend/src/app/\(account\)/settings
mkdir -p frontend/src/app/\(account\)/templates
mkdir -p frontend/src/app/\(auth\)/login
mkdir -p frontend/src/app/\(auth\)/register
mkdir -p frontend/src/app/\(auth\)/verify
mkdir -p frontend/src/app/\(shop\)/cart
mkdir -p frontend/src/app/\(shop\)/categories/\[slug\]
mkdir -p frontend/src/app/\(shop\)/checkout/success
mkdir -p frontend/src/app/\(shop\)/deals
mkdir -p frontend/src/app/\(shop\)/products/\[handle\]
mkdir -p frontend/src/app/\(shop\)/search
mkdir -p frontend/src/app/api/auth/login
mkdir -p frontend/src/app/api/auth/logout
mkdir -p frontend/src/app/api/auth/register
mkdir -p frontend/src/app/api/auth/session
mkdir -p frontend/src/app/api/cart/items/\[id\]
mkdir -p frontend/src/app/api/categories/\[slug\]
mkdir -p frontend/src/app/api/checkout/complete
mkdir -p frontend/src/app/api/orders/\[id\]
mkdir -p frontend/src/app/api/products/\[handle\]
mkdir -p frontend/src/app/api/webhooks/erpnext
mkdir -p frontend/src/app/api/webhooks/medusa
mkdir -p frontend/src/components/feedback
mkdir -p frontend/src/components/layout
mkdir -p frontend/src/components/navigation
mkdir -p frontend/src/components/ui
mkdir -p frontend/src/features/auth/components
mkdir -p frontend/src/features/auth/hooks
mkdir -p frontend/src/features/auth/types
mkdir -p frontend/src/features/cart/components
mkdir -p frontend/src/features/cart/hooks
mkdir -p frontend/src/features/cart/store
mkdir -p frontend/src/features/cart/types
mkdir -p frontend/src/features/category/components
mkdir -p frontend/src/features/category/hooks
mkdir -p frontend/src/features/category/types
mkdir -p frontend/src/features/checkout/components
mkdir -p frontend/src/features/checkout/hooks
mkdir -p frontend/src/features/checkout/types
mkdir -p frontend/src/features/checkout/utils
mkdir -p frontend/src/features/deal/components
mkdir -p frontend/src/features/deal/hooks
mkdir -p frontend/src/features/deal/types
mkdir -p frontend/src/features/order/components
mkdir -p frontend/src/features/order/hooks
mkdir -p frontend/src/features/order/types
mkdir -p frontend/src/features/product/components
mkdir -p frontend/src/features/product/hooks
mkdir -p frontend/src/features/product/types
mkdir -p frontend/src/features/product/utils
mkdir -p frontend/src/features/search/components
mkdir -p frontend/src/features/search/hooks
mkdir -p frontend/src/features/search/utils
mkdir -p frontend/src/features/wholesale/components
mkdir -p frontend/src/features/wholesale/hooks
mkdir -p frontend/src/features/wholesale/types
mkdir -p frontend/src/hooks
mkdir -p frontend/src/lib
mkdir -p frontend/src/locales
mkdir -p frontend/src/providers
mkdir -p frontend/src/public
mkdir -p frontend/src/services
mkdir -p frontend/src/styles
mkdir -p frontend/src/utils
mkdir -p plugins/medusa-delivery-zones/src/models
mkdir -p plugins/medusa-delivery-zones/src/services
mkdir -p plugins/medusa-delivery-zones/src/types
mkdir -p plugins/medusa-order-templates/src/models
mkdir -p plugins/medusa-order-templates/src/services
mkdir -p plugins/medusa-order-templates/src/types
mkdir -p plugins/medusa-wholesale/src/models
mkdir -p plugins/medusa-wholesale/src/services
mkdir -p plugins/medusa-wholesale/src/types
mkdir -p scripts/deploy
mkdir -p scripts/dev
mkdir -p scripts/migrate
mkdir -p scripts/seed
mkdir -p scripts/sync
