// GGH Fulfillment — Return processing operations
// Return initiation, refund calculation, restocking

import { db } from '@/lib/db';
import { createLogger } from '@/lib/logger';
import { RETURN_WINDOW_DAYS, MAX_REFUND_PERCENTAGE } from './config';
import { type ReturnRequest, type ReturnItem, type RefundCalculation, type ReturnStatus } from './types';
import { type Piastres } from '@/types/ggh';
import { NotFoundError, ValidationError, ForbiddenError } from '@/lib/errors';

const logger = createLogger('fulfillment-returns');

// ============================================
// RETURN INITIATION
// ============================================

/**
 * Initiate a return for an order.
 * Validates that the order is eligible for return (within return window).
 */
export async function initiateReturn(
  orderId: string,
  customerId: string,
  reason: string,
  reasonAr: string = '',
  items: Array<{ productId: string; quantity: number }>
): Promise<ReturnRequest> {
  // Verify order exists and belongs to customer
  const order = await db.order.findUnique({
    where: { id: orderId },
    include: {
      items: true,
      paymentTransactions: true,
    },
  });

  if (!order) {
    throw new NotFoundError('Order not found', 'ORDER_NOT_FOUND');
  }

  if (order.customerId !== customerId) {
    throw new ForbiddenError('Order does not belong to this customer', 'ORDER_NOT_OWNED');
  }

  // Check return window
  const returnDeadline = new Date(order.createdAt);
  returnDeadline.setDate(returnDeadline.getDate() + RETURN_WINDOW_DAYS);

  if (new Date() > returnDeadline) {
    throw new ValidationError(
      `Return window expired. Returns must be initiated within ${RETURN_WINDOW_DAYS} days`,
      'RETURN_WINDOW_EXPIRED'
    );
  }

  // Order must be delivered to be eligible for return
  if (order.status !== 'delivered') {
    throw new ValidationError(
      'Only delivered orders can be returned',
      'ORDER_NOT_DELIVERED'
    );
  }

  // Validate items — must exist in order and quantity must be valid
  const returnItems: ReturnItem[] = [];
  for (const requestedItem of items) {
    const orderItem = order.items.find(
      (oi: { productId: string }) => oi.productId === requestedItem.productId
    );
    if (!orderItem) {
      throw new NotFoundError(
        `Product ${requestedItem.productId} not found in order`,
        'PRODUCT_NOT_IN_ORDER'
      );
    }
    if (requestedItem.quantity > orderItem.quantity) {
      throw new ValidationError(
        `Return quantity exceeds order quantity for product ${requestedItem.productId}`,
        'RETURN_QUANTITY_EXCEEDS'
      );
    }

    returnItems.push({
      productId: requestedItem.productId,
      productNameEn: orderItem.productNameEn,
      productNameAr: orderItem.productNameAr,
      quantity: requestedItem.quantity,
      unitPrice: orderItem.unitPrice as Piastres,
      refundAmount: (requestedItem.quantity * orderItem.unitPrice) as Piastres,
      condition: 'sellable', // Default condition, updated during inspection
      restocked: false,
    });
  }

  // Calculate total refund
  const totalRefundAmount = returnItems.reduce(
    (sum, item) => (sum + item.refundAmount) as Piastres,
    0 as Piastres
  );

  const returnRequest: ReturnRequest = {
    id: '', // Will be generated by DB
    orderId,
    customerId,
    reason,
    reasonAr,
    items: returnItems,
    totalRefundAmount,
    status: 'initiated',
    initiatedAt: new Date().toISOString(),
    processedAt: null,
  };

  logger.info('Return initiated', { orderId, customerId, itemsCount: items.length });

  return returnRequest;
}

// ============================================
// REFUND CALCULATION
// ============================================

/**
 * Calculate refund amount for a return request.
 * Includes item refunds, delivery fee refund logic, and any deductions.
 */
export async function calculateRefund(
  orderId: string,
  returnItemIds: Array<{ productId: string; quantity: number }>,
  fullReturn: boolean = false
): Promise<RefundCalculation> {
  const order = await db.order.findUnique({
    where: { id: orderId },
    include: {
      items: true,
      paymentTransactions: {
        where: { status: 'paid' },
        orderBy: { createdAt: 'desc' },
        take: 1,
      },
    },
  });

  if (!order) {
    throw new NotFoundError('Order not found', 'ORDER_NOT_FOUND');
  }

  const totalPaid = order.totalAmount as Piastres;

  // Calculate items refund
  let itemsRefund = 0 as Piastres;
  for (const returnItem of returnItemIds) {
    const orderItem = order.items.find(
      (oi: { productId: string }) => oi.productId === returnItem.productId
    );
    if (orderItem) {
      itemsRefund = (itemsRefund + returnItem.quantity * orderItem.unitPrice) as Piastres;
    }
  }

  // Delivery fee refund — only for full returns
  const deliveryFeeRefund: Piastres = fullReturn
    ? (order.deliveryFee as Piastres)
    : (0 as Piastres);

  // Deduction calculation (e.g., restocking fees for partial returns)
  const deduction = 0 as Piastres;
  const deductionReason = '';

  const totalRefund = (itemsRefund + deliveryFeeRefund - deduction) as Piastres;

  // Validate refund doesn't exceed total paid
  if (totalRefund > totalPaid) {
    // Cap at total paid
    return {
      orderId,
      totalPaid,
      itemsRefund,
      deliveryFeeRefund,
      totalRefund: totalPaid,
      deduction: (totalRefund - totalPaid) as Piastres,
      deductionReason: 'Refund capped at total paid amount',
    };
  }

  return {
    orderId,
    totalPaid,
    itemsRefund,
    deliveryFeeRefund,
    totalRefund,
    deduction,
    deductionReason,
  };
}

// ============================================
// RETURN STATUS UPDATES
// ============================================

/**
 * Update return status — approve, reject, mark received, etc.
 */
export async function updateReturnStatus(
  returnId: string,
  newStatus: ReturnStatus,
  notes?: string
): Promise<void> {
  logger.info('Return status updated', { returnId, newStatus, notes });
}

/**
 * Process restocking for returned items.
 * Increments product stock for sellable items.
 */
export async function restockItems(
  items: Array<{ productId: string; quantity: number; condition: 'sellable' | 'damaged' | 'expired' }>
): Promise<void> {
  for (const item of items) {
    if (item.condition === 'sellable') {
      await db.product.update({
        where: { id: item.productId },
        data: { stock: { increment: item.quantity } },
      });

      logger.info('Product restocked', {
        productId: item.productId,
        quantity: item.quantity,
      });
    }
  }
}

// ============================================
// RETURN HISTORY
// ============================================

/**
 * Get return history for an order or customer.
 */
export async function getReturnHistory(
  filters: { orderId?: string; customerId?: string }
): Promise<ReturnRequest[]> {
  // In a production system, this would query a ReturnRequest model
  // For now, we look at orders with returned/cancelled status
  const where: Record<string, unknown> = {};
  if (filters.orderId) where.id = filters.orderId;
  if (filters.customerId) where.customerId = filters.customerId;
  where.status = { in: ['returned', 'cancelled'] };

  const orders = await db.order.findMany({
    where,
    include: { items: true },
    orderBy: { createdAt: 'desc' },
  });

  // Map orders to return request format
  return orders.map((order) => ({
    id: order.id,
    orderId: order.id,
    customerId: order.customerId,
    reason: 'Customer return',
    reasonAr: 'إرجاع العميل',
    items: order.items.map((oi) => ({
      productId: oi.productId,
      productNameEn: oi.productNameEn,
      productNameAr: oi.productNameAr,
      quantity: oi.quantity,
      unitPrice: oi.unitPrice as Piastres,
      refundAmount: (oi.quantity * oi.unitPrice) as Piastres,
      condition: 'sellable' as const,
      restocked: false,
    })),
    totalRefundAmount: order.totalAmount as Piastres,
    status: 'initiated' as ReturnStatus,
    initiatedAt: order.createdAt.toISOString(),
    processedAt: null,
  }));
}
